<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Admin Page</title>
</head>
<body>
<%
    if ((session.getAttribute("user") == null)) {
%>
You are not logged in<br/>
<a href="AdminLogin.jsp">Please Login</a>
<%} else {
%>
	<h1>Welcome admin <%=session.getAttribute("user") %>! </h1>
	<p><a href="AdminLogout.jsp">Log out</a></p>
	<p><a href="EditCustomers.jsp">Edit customers</a></p>
	<p><a href="EditCustomerReps.jsp">Edit customer representatives</a></p>

	<form action="SalesReport.jsp" method="POST">
		Sales report for a particular month. Month format: 01 = January, 12 = December, etc.
		<br>
		<input type="text" name="month" placeholder="Month"> 
		<input type="submit" value="Search">
	</form>
	<br>
	<form action="ReservationsByFlightNum.jsp" method="POST">
		Get all reservations by flight number: 
		<br>
		<input type="text" name="airline_id" placeholder="Airline ID">
		<br>
		<input type="text" name="aircraft_id" placeholder="Aircraft ID"> 
		<input type="submit" value="Search">
	</form>
	<br>
	<form action="ReservationsByCustomerName.jsp" method="POST">
		Get all reservations of a customer: 
		<br>
		<input type="text" name="first_name" placeholder="Customer's first name">
		<br>
		<input type="text" name="last_name" placeholder="Customer's last name"> 
		<input type="submit" value="Search">
	</form>
	<br>
	<form action="RevenueByFlight.jsp" method="POST">
		Revenue generated by flight: 
		<br><input type="text" name="airline_id" placeholder="Enter Airline ID">
		<br> 
		<input type="text" name="aircraft_id" placeholder="Enter Aircraft ID"> 
		<input type="submit" value="Search">
	</form>
	<br>
		<p><a href="RevenueByAirline.jsp">Get revenue by airline</a></p>
		<p><a href="RevenueByCustomer.jsp">Get revenue by customer</a></p>
	<br>
	<form action="HighestRevenueCustomer.jsp" method="POST">
		Find the customer that generated the most revenue: 
		<br>
		<input type="submit" value="Search">
	</form>
	<br>
	<form action="MostActiveFlights.jsp" method="POST">
		Find the most active flights (had the most tickets bought): 
		<br>
		<input type="submit" value="Search">
	</form>
<%
    }
%>
</body>
</html>